### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by viranch** [larsks/dockerize#2]
It'd be nice to have instructions in the README for installing dockerize.

EDIT: Preferably, without having to clone the git repository.

**Comment by brbsix** [comment]
Assuming you have `pip` installed (and you certainly should if you do any work with Python), you can install `dockerize` locally with the following command:

```
pip2 install --user git+http://github.com/larsks/dockerize.git
```

However the best case scenario would be to have the package hosted on [PyPi](https://pypi.python.org) (the Python package repository). This would permit easy install (e.g. `pip2 install --user dockerize`).

I've forked the repo and made changes so that it can be easily packaged and uploaded to PyPi. I'll submit a pull request and see if @larsks is interested in submitting it to PyPi. Alternatively, I can submit it myself. I already have a number of packages/library on PyPi (and have a corresponding workflow) so I don't mind taking care of it if need be.

I will also update the README with installation information.

My fork is at https://github.com/brbsix/dockerize

**Comment by larsks** [comment]
Why not just submit a PR and see what happens?

**Comment by brbsix** [comment]
I was just about to submit one when I saw this. Should have it ready in a few minutes. :)

**Comment by larsks** [comment]
This package is now available on pypi: https://pypi.python.org/pypi/undocker
